language: php

services:
  - mysql

jobs:
- language: php
  os: linux
  dist: trusty
  php:
    - '5.4'
  script:
    - composer require laravel/laravel:4.2
- language: php
  os: linux
  dist: trusty
  php:
    - '5.4'
  script:
    - composer require laravel/laravel:5.0
- language: php
  os: linux
  dist: trusty
  php:
    - '5.5'
  script:
    - composer require laravel/laravel:5.1
- language: php
  os: linux
  dist: trusty
  php:
    - '5.5'
  script:
    - composer require laravel/laravel:5.2
- language: php
  os: linux
  dist: trusty
  php:
    - '5.6'
  script:
    - composer require laravel/laravel:5.3
- language: php
  os: linux
  dist: trusty
  php:
    - '5.6'
  script:
    - composer require laravel/laravel:5.4
- language: php
  os: linux
  php:
    - '7.0'
  script:
    - composer require laravel/laravel:5.5

sudo: false

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
