language: php

services:
  - mysql

branches:
- master
- 5.1
- 5.2
- 5.3

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
