language: php

services:
  - mysql

jobs:
- language: php
  os: linux
  dist: trusty
  env:
    - PHP_VERSION=5.4
    - LARAVEL_VERSION=4.2
  php:
    - '5.4'
- language: php
  os: linux
  dist: trusty
  env:
    - PHP_VERSION=5.4
    - LARAVEL_VERSION=5.0
  php:
    - '5.4'
- language: php
  os: linux
  dist: trusty
  env:
    - PHP_VERSION=5.5
    - LARAVEL_VERSION=5.1
  php:
    - '5.5'
- language: php
  os: linux
  dist: trusty
  env:
    - PHP_VERSION=5.5
    - LARAVEL_VERSION=5.2
  php:
    - '5.5'
- language: php
  os: linux
  dist: trusty
  env:
    - PHP_VERSION=5.6
    - LARAVEL_VERSION=5.3
  php:
    - '5.6'
- language: php
  os: linux
  dist: trusty
  env:
    - PHP_VERSION=5.6
    - LARAVEL_VERSION=5.4
  php:
    - '5.6'
- language: php
  os: linux
  env:
    - PHP_VERSION=7.0
    - LARAVEL_VERSION=5.5
  php:
    - '7.0'
- language: php
  os: linux
  env:
    - PHP_VERSION=7.1
    - LARAVEL_VERSION=5.6
  php:
    - '7.1'
- language: php
  os: linux
  env:
    - PHP_VERSION=7.1
    - LARAVEL_VERSION=5.7
  php:
    - '7.1'
- language: php
  os: linux
  env:
    - PHP_VERSION=7.1
    - LARAVEL_VERSION=5.8
  php:
    - '7.1'
- language: php
  os: linux
  env:
    - PHP_VERSION=7.2
    - LARAVEL_VERSION=6.0
  php:
    - '7.2'
- language: php
  os: linux
  env:
    - PHP_VERSION=7.3
    - LARAVEL_VERSION=6.0
  php:
    - '7.3'
- language: php
  os: linux
  env:
    - PHP_VERSION=7.4
    - LARAVEL_VERSION=6.0
  php:
    - '7.4'

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - COMPOSER_MEMORY_LIMIT=-1 composer require laravel/laravel:^$LARAVEL_VERSION

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
  - bash <(curl -s https://codecov.io/bash)
