language: php

services:
  - mysql

jobs:
- language: php
  os: linux
  dist: trusty
  php:
    - '5.4'
  before_install:
    - composer require laravel/laravel:4.2
- language: php
  os: linux
  dist: trusty
  php:
    - '5.4'
  before_install:
    - composer require laravel/laravel:5.0
- language: php
  os: linux
  dist: trusty
  php:
    - '5.5'
  before_install:
    - composer require laravel/laravel:5.1
- language: php
  os: linux
  dist: trusty
  php:
    - '5.5'
  before_install:
    - composer require laravel/laravel:5.2
- language: php
  os: linux
  dist: trusty
  php:
    - '5.6'
  before_install:
    - composer require laravel/laravel:5.3
- language: php
  os: linux
  dist: trusty
  php:
    - '5.6'
  before_install:
    - composer require laravel/laravel:5.4
- language: php
  os: linux
  php:
    - '7.0'
  before_install:
    - composer require laravel/laravel:5.5

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
