name: 4.2

on: [push]

jobs:
  build:
    name: "Build package for Laravel 4.2 and PHP 5.4"
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.4'
      - name: Install Laravel
        run: COMPOSER_MEMORY_LIMIT=-1 composer require laravel/laravel:^$LARAVEL_VERSION
        env:
          LARAVEL_VERSION: '4.2'
      - name: Install PHPUnit
        run: COMPOSER_MEMORY_LIMIT=-1 composer require phpunit/phpunit
      - name: Run Tests
        run: vendor/bin/phpunit
