name: Laravel 5.2

on: [push]

jobs:
  build:
    strategy:
      matrix:
        php: [5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4]
    name: "Laravel 5.2"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install Laravel
        run: COMPOSER_MEMORY_LIMIT=-1 composer require laravel/laravel:^$LARAVEL_VERSION
        env:
          LARAVEL_VERSION: '5.2'
      - name: Install PHPUnit
        run: COMPOSER_MEMORY_LIMIT=-1 composer require phpunit/phpunit
      - name: Run Tests
        run: vendor/bin/phpunit
